-- 回收订单表
CREATE TABLE `recycle_order` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `no` varchar(50) NOT NULL COMMENT '订单编号',
  `type` varchar(20) NOT NULL COMMENT '订单类型：purchase-采购订单，transport-运输订单，process-加工订单，sales-销售订单，storage-仓储订单，other-其他订单',
  `status` varchar(20) NOT NULL COMMENT '订单状态：processing-执行中，completed-已结算',
  `start_time` datetime NOT NULL COMMENT '起始时间',
  `end_time` datetime NOT NULL COMMENT '结束时间',
  `identify_code` varchar(100) DEFAULT NULL COMMENT '订单识别码',
  `processor` varchar(100) NOT NULL COMMENT '经办人',
  `processor_phone` varchar(20) NOT NULL COMMENT '经办人电话',
  `total_amount` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '订单总金额',
  `order_node_time` datetime DEFAULT NULL COMMENT '订单节点时间',
  `order_node_img` varchar(500) DEFAULT NULL COMMENT '订单图片',
  `order_node_pickup_location` varchar(200) DEFAULT NULL COMMENT '订单节点提货地点',
  `order_node_delivery_location` varchar(200) DEFAULT NULL COMMENT '订单节点交付地点',
  `contract_no` varchar(50) NOT NULL COMMENT '合同编号',
  `contract_reference_price` decimal(15,2) DEFAULT '0.00' COMMENT '合同参考价格',
  `contract_name` varchar(200) NOT NULL COMMENT '合同名称',
  `contract_partner` varchar(20) DEFAULT NULL COMMENT '合同合作方：甲方，乙方',
  `party_a` varchar(200) DEFAULT NULL COMMENT '甲方',
  `party_b` varchar(200) DEFAULT NULL COMMENT '乙方',
  `contract_price` decimal(15,2) DEFAULT '0.00' COMMENT '合同金额',
  `warehouse_address` varchar(500) DEFAULT NULL COMMENT '仓库地址',
  `delivery_address` varchar(500) DEFAULT NULL COMMENT '交付地址',
  `flow_direction` varchar(20) DEFAULT NULL COMMENT '流转方向：入库，出库',
  `payment_account` varchar(200) DEFAULT NULL COMMENT '走款账号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标识：0-未删除，1-已删除',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_no` (`no`),
  KEY `idx_type` (`type`),
  KEY `idx_status` (`status`),
  KEY `idx_contract_no` (`contract_no`),
  KEY `idx_processor` (`processor`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回收订单表'; 